export default `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque urna est, euismod quis feugiat vitae, elementum in ex. Quisque vulputate, felis eu gravida sollicitudin, erat ante tincidunt lorem, sed tristique felis dolor non dui. Nullam elementum ex vitae semper pulvinar. Nullam condimentum fringilla magna, eu consequat eros viverra et. Nunc cursus porta imperdiet. Aliquam erat volutpat. Vivamus dignissim elementum sapien, sed dictum augue condimentum vel. Fusce tellus sapien, fermentum ut mattis sed, malesuada at diam. Etiam vitae consectetur elit, non viverra diam. Integer sagittis nunc ante, ut tempor lectus elementum et. Pellentesque ut consectetur urna. Vestibulum eu convallis sapien. Nam ac nisl efficitur quam iaculis aliquam. Donec at metus nisi.

Aenean elementum arcu nisi, quis luctus lectus sodales id. Ut sodales ac ligula sed convallis. Aenean accumsan felis non lorem maximus, eget blandit massa mollis. Nullam non justo elementum, vulputate justo et, scelerisque odio. Aenean rhoncus nisl sem, in luctus lorem interdum nec. Nullam non volutpat lorem. Pellentesque vestibulum vestibulum massa, fermentum vulputate velit hendrerit eget. In laoreet turpis ut erat hendrerit vestibulum sit amet a risus. Fusce euismod elit sit amet nisi fermentum, ac congue dui pharetra.

Praesent nec diam vel ligula fermentum tristique. Integer vestibulum ullamcorper mi, ac convallis leo volutpat id. Proin non sem vitae neque faucibus consequat in ut sem. Aliquam erat volutpat. Fusce dui justo, convallis volutpat facilisis sagittis, dapibus non purus. Nunc a finibus felis. Integer eros diam, tempus laoreet fermentum ut, pellentesque in nibh.

Integer ac placerat nisi. Nulla dapibus libero nulla, elementum venenatis arcu porttitor sit amet. In accumsan, dui in tincidunt efficitur, purus mi pellentesque quam, et pharetra leo ipsum non magna. Mauris blandit orci purus, ultrices cursus neque malesuada ac. Nam aliquet ante sit amet turpis lacinia, sit amet lacinia elit lobortis. Nam in diam purus. Aenean mollis finibus sapien, iaculis eleifend sapien hendrerit at. Donec quis facilisis lorem. Aliquam suscipit dolor tellus, et sodales nunc varius in. Maecenas vehicula nulla a urna condimentum sagittis.

Etiam lobortis pulvinar tortor non porttitor. Curabitur porta quis elit a pulvinar. Nulla leo lectus, suscipit ac volutpat et, sollicitudin condimentum nulla. Cras mattis consequat mauris nec volutpat. Duis bibendum hendrerit nisi. Praesent a diam elit. In hac habitasse platea dictumst. Integer vel rutrum odio, ac porta metus. Nam luctus odio a mi aliquet, eget auctor leo mattis. Vivamus ultricies venenatis ex, bibendum volutpat enim tempus vitae.`;
